### ISSUE TITLE
Custom Properties

### ISSUE THREAD

**Issue by TheSilkMiner** [SandboxPowered/Sandbox#17]
## Is your feature request related to a problem? Please describe.
Vanilla's Blockstate properties are sure numerous, but they may not suit all cases.
For this reason, I'd like to have the possibility of creating custom properties.
At the moment, this results in a crash due to a `ClassCastException`, though.

## Describe the solution you'd like
Creating a subclass of `Property<T>` and then specifying it directly in the `Block#addProperties` method.
Also, I'd argue that a `Property<Direction>` should be supplied natively, either with all directions or just with a single one, since many users may want to have blocks with a facing, but this something more related to the API rather than the implementation itself.

## Describe alternatives you've considered
Mixing and matching vanilla properties doesn't really seem ideal, but it is an option for the time being.

## Additional context
**Sandbox version**: 0.2.1-SNAPSHOT (API and implementation)

**Comment by adrwa** [comment]
Can you show the code you used for your block?
