### ISSUE TITLE
Can't register any blocks or items

### ISSUE THREAD

**Issue by LemmaEOF** [SandboxPowered/Sandbox#9]
Currently, any attempts to register blocks or items are throwing a `RuntimeException` from `WrappingUtil`. It seems like `bClass.isInstance(a)` in `WrappingUtil.castOrWrap` is failing, which then causes it to try `WrappingUtil.getWrapped`, which throws because the object isn't `instanceof WrappedInjection`, or something. As it is, Sandbox is basically unusable.

**Comment by UpcraftLP** [comment]
fixed in https://github.com/SandboxPowered/Sandbox/commit/2266dd3cbc0cc5cce742bb2e44bed74614d8d100
